```{r}
library(dplyr)
library(ggplot2)
```

--- Melamed et al. ---
```{r}
# Mean and SD Regression Equations
mean_hc_male <- function(X) {
  eq <- 2.21 * X^(-1) - 7.2 * X^(-0.05 ) - 0.0001 * X^(2) + 3.8
}

mean_hc_fem <- function(X) {
  eq <- 121.3 * X^(-2) - 26 * X^(-1) - 0.0001 * X^(2) + 3.2
}

sd_hc_male <- function(X) {
  eq <- -80.5 * X^(-1) + 11.6
}

sd_hc_fem <- function(X) {
  eq <- -91.5 * X^(-1) + 11.8
}

# Mean and SD Regression Equations (AC)
mean_ac_male <- function(X) {
  eq <- -18.2 * X^(-2) - 5.1 * X^(-0.5) + 3.3
}

mean_ac_fem <- function(X) {
  eq <- -3.4 * X^(-0.5) + 0.02 * X-0.0002 * X^(2) + 2.6
}

sd_ac_male <- function(X) {
  eq <- 5.0 * X^(0.5) - 14.8
}

sd_ac_fem <- function(X) {
  eq <- 4.8 * X^ (0.5) - 13.5
}

# Mean and SD Regression Equations (FL)
mean_fl_male <- function(X) {
  eq <- -43.2 * X^(-2) - 11.5 * X^(-1) + 2.2
}

mean_fl_fem <- function(X) {
  eq <- -15.7 * X^(-1) - 0.00002 * X^(2) + 2.3
}

sd_fl_male <- function(X) {
  eq <- -8.1 * X^(-0.5) + 3.7
}

sd_fl_fem <- function(X) {
  eq <- -232.7 * X^(-2) + 2.5
}

# X-values 
mel_x <- seq(11, 40)
```

--- Mean Differences ---

HC (mm)---
```{r}
gal_diff <- numeric(nrow(gal))

# Mean differences for each row
for (i in 1:nrow(gal)) {
  gal_diff[i] <- gal[i, "C50.mm."] - gal[i, "C50.mm..1"]
}

gal_diff
```

```{r}
keen_diff <- numeric(nrow(keen))

# Mean differences for each row
for (i in 1:nrow(keen)) {
  # Convert cm to mm
  boys_mm <- keen[i, "head_circ_boys_cm"] * 10
  girls_mm <- keen[i, "head_circ_girls_cm"] * 10
  keen_diff[i] <- mean(boys_mm - girls_mm, na.rm = TRUE)
}

keen_diff
```

```{r}
sch_diff <- numeric(nrow(sch))

# Mean differences for each row
for (i in 1:nrow(sch)) {
  sch_diff[i] <- mean(sch[i, "M_Mean..mm."] - sch[i, "F_Mean..mm."], na.rm = TRUE)
}

sch_diff
```

```{r}
yeo_diff <- numeric(nrow(yeo))

# Mean differences for each row
for (i in 1:nrow(yeo)) {
  yeo_diff[i] <- mean(yeo[i, "X50th.Centile_Male.mm."] - yeo[i, "X50th.Centile_Female.mm."], na.rm = TRUE)
}

yeo_diff
```

```{r}
# Output values for each equation with X values (11 to 40)
mel_output_male <- mean_hc_male(mel_x)
mel_output_fem <- mean_hc_fem(mel_x)
mel_output_male2 <- mean_ac_male(mel_x)
mel_output_fem2 <- mean_ac_fem(mel_x)
mel_output_male3 <- mean_fl_male(mel_x)
mel_output_fem3 <- mean_fl_fem(mel_x)

# Differences for each X value
mel_diff <- mel_output_fem - mel_output_male
mel_ac_diff <- mel_output_fem2 - mel_output_male2
mel_fl_diff <- mel_output_fem3 - mel_output_male3

mel_diff
mel_ac_diff
mel_fl_diff
```

```{r}
# Output values for each equation using X values
output_male_new <- mean_hc_male(mel_x)
output_female_new <- mean_hc_fem(mel_x)

# Differences for each X value
differences <- output_female_new - output_male_new

plot(mel_x, differences, type = "l", xlab = "Gestation Weeks", ylab = "Difference (female - male)")
``` 
```{r}
# Set Y values
Y_values_male <- mean_hc_male(mel_x)
Y_values_female <- mean_hc_fem(mel_x)

# Plot regression equations
plot(mel_x, Y_values_male, type = 'l', col = 'blue', xlab = 'Gestation Weeks', ylab = 'Mean Head Circumference', ylim = c(min(Y_values_female, Y_values_male), max(Y_values_female, Y_values_male)))
lines(mel_x, Y_values_female, col = 'red')  
legend('topright', legend = c('Male', 'Female'), col = c('blue', 'red'), lty = 1)
xlabel <- expression(paste('Gestation Weeks'))
ylabel <- expression(paste('Mean Head Circumference'))
mtext(xlabel, side = 1, line = 3)
mtext(ylabel, side = 2, line = 3)
title(main = title, line = 0.5)
```
weight (g)---
```{r}
galefw_diff <- numeric(nrow(galefw))

# Mean difference for each row
for (i in 1:nrow(galefw)) {
  galefw_diff[i] <- mean(galefw[i, "boys_C50.g."] - galefw[i, "girls_C50.g."], na.rm = TRUE)
}

galefw_diff
```

```{r}
schefw_diff <- numeric(nrow(schefw))

# Mean difference for each row
for (i in 1:nrow(schefw)) {
  schefw_diff[i] <- mean(schefw[i, "M_Mean..mm."] - schefw[i, "F_Mean..mm."], na.rm = TRUE)
}

schefw_diff
```
```{r}
schac_diff <- numeric(nrow(sch_ac))

# Mean difference for each row
for (i in 1:nrow(sch_ac)) {
  schac_diff[i] <- mean(sch_ac[i, "M_mean"] - sch_ac[i, "F_mean"], na.rm = TRUE)
}

schac_diff
```

```{r}
keenefw_diff <- numeric(nrow(keen))

# Mean difference for each row
for (i in 1:nrow(keen)) {
  keenefw_diff[i] <- mean(keen[i, "weight_boys_g"] - keen[i, "weight_girls_g"], na.rm = TRUE)
}

keenefw_diff
```

```{r}
keen_diffl <- numeric(nrow(keen))

# Mean difference for each row
for (i in 1:nrow(keen)) {
  keen_diffl[i] <- mean(keen[i, "length_boys_cm"] - keen[i, "length_girls_cm"], na.rm = TRUE)
}

keen_diffl
```

--- Standard Deviation ---

Standard deviation for each gestational week
```{r}
# Male
yeo_3m <- yeo$X3rd.Centile_Male.mm.
yeo_97m <- yeo$X97th.Centile_Male.mm.

# Estimate standard deviation
yeo_sdvalsm <- (yeo_97m - yeo_3m) / (2 * qnorm(0.975))

yeo_sdvalsm
```

```{r}
# Female
yeo_3f <- yeo$X3rd.Centile_Fenale.mm.
yeo_97f <- yeo$X97th.Centile_Female.mm.

# Estimate standard deviation
yeo_sdvalsf <- (yeo_97f - yeo_3f) / (2 * qnorm(0.975))

yeo_sdvalsf
```
```{r}
# Male
gal_10m <- gal$C10.mm.
gal_90m <- gal$C90.mm.

# Estimate standard deviation
gal_sdvalsm <- (gal_90m - gal_10m) / (2 * qnorm(0.975))

gal_sdvalsm
```

```{r}
# Female
gal_10f <- gal$C10.mm..1
gal_90f <- gal$C90.mm..1

# Estimate standard deviation
gal_sdvalsf <- (gal_90f - gal_10f) / (2 * qnorm(0.975))

gal_sdvalsf
```


--efw
```{r}
# Males
galefwm_10 <- galefw$boys_C10.g.
galefwm_90 <- galefw$boys_C90.g.

# Estimate standard deviation
galefw_sdvalsm <- (galefwm_90 - galefwm_10) / (2 * qnorm(0.975))

galefw_sdvalsm
```

```{r}
# Females
galefwf_10 <- galefw$girls_C10.g.
galefwf_90 <- galefw$girls_C90.g.

# Estimate standard deviation
galefw_sdvalsf <- (galefwf_90 - galefwf_10) / (2 * qnorm(0.975))

galefw_sdvalsf
```

--- Effect Sizes ---

--Pooled SD (HC)
```{r}
keenFSD <- keen$head_circsd_girls_cm * 10
keenMSD <- keen$head_circsd_boys_cm * 10
```

```{r}
yeo_pSD <- sqrt((yeo_sdvalsm^2 + yeo_sdvalsf^2)/2)
gal_pSD <- sqrt((gal_sdvalsf^2 + gal_sdvalsm^2)/2)
sch_pSD <- sqrt((sch$F_SD..mm.^2 + sch$M_SD..mm.^2)/2)
schac_pSD <- sqrt((sch_ac$F_SD^2 + sch_ac$M_SD^2)/2)
keen_pSD <- sqrt((keenFSD^2 + keenMSD^2)/2)
mel_pSD <- sqrt((sd_hc_fem(mel_x)^2 + sd_hc_male(mel_x)^2)/2)
mel_ac_pSD <- sqrt((sd_ac_fem(mel_x)^2 + sd_ac_male(mel_x)^2)/2)
mel_fl_pSD <- sqrt((sd_fl_fem(mel_x)^2 + sd_fl_male(mel_x)^2)/2)
```

-- HC effect sizes
```{r}
yeoES <- yeo_diff/yeo_pSD
galES <- gal_diff/gal_pSD
schES <- sch_diff/sch_pSD
keenES <- keen_diff/keen_pSD
melES <- mel_diff/mel_pSD
```

-- AC/FL Effect sizes --

```{r}
melESac <- mel_ac_diff/mel_ac_pSD
melESfl <- mel_fl_diff/mel_fl_pSD
```

```{r}
schacES <- schac_diff/schac_pSD
```

--Dataframes 

```{r}
yeoESvAge <- data.frame(x = yeo$Gestational.Age, y = yeoES)
galESvAge <- data.frame(x = gal$GA.mm, y = galES)
schESvAge <- data.frame(x = sch$F_GA..Weeks., y = schES)
keenESvAge <- data.frame(x = keen$gestationweeks, y = keenES)
melESvAge <- data.frame(x = mel_x, y = melES)
``` 


```{r}
melESvAgeAC <- data.frame(x = mel_x, y = melESac)
melESvAgeFL <- data.frame(x = mel_x, y = melESfl)
```

```{r}
schacvAge <- data.frame(x = sch_ac$gestationweeks, y = schacES)
```

--- Plot Mel Effect Size Age and Femur Length ---
```{r}
plot(melESvAgeFL$x, melESvAgeFL$y, type = "l", col = "orange", xlab = "Gestational Age", ylab = "Effect Size",
     main = "Effect Size and Femur Length")
```
```{r}
plot(schacvAge$x, schacvAge$y, type = "l", col = "blue", xlab = "Gestation Weeks", ylab = "Effect Size",
     main = "Effect Size (Abdominal Circumference) vs Gestational Weeks")
lines(melESvAgeAC$x, melESvAgeAC$y, col = "red")
legend("topright", legend = c("schacES", "melESac"), col = c("blue", "red"), lty = 1)
```

```{r}
combinedES <- rbind(
  transform(yeoESvAge, group = "yeo"),
  transform(galESvAge, group = "gal"),
  transform(schESvAge, group = "sch"),
  transform(keenESvAge, group = "keen"),
  transform(melESvAge, group = "mel")
)

ggplot(combinedES, aes(x = x, y = y, color = group)) +
  geom_line() +
  labs(title = "Effect Size vs Gestational Age",
       x = "Gestational Age",
       y = "Effect Size") +
  theme_minimal()
```
```{r}
combinedES2 <- rbind(
  transform(yeoESvAge, dataset = "Yeo"),
  transform(galESvAge, dataset = "Gal"),
  transform(schESvAge, dataset = "Sch"),
  transform(keenESvAge, dataset = "Keen"),
  transform(melESvAge, dataset = "Mel")
)

ggplot(combinedES2, aes(x = x, y = y, color = dataset)) +
  geom_line() +
  labs(title = "Effect Size vs Gestational Age",
       x = "Gestational Age",
       y = "Effect Size") +
  facet_wrap(~dataset, scales = "free_y") +
  theme_minimal()
```
```{r}
combinedES3 <- rbind(
  transform(yeoESvAge, dataset = "Yeo"),
  transform(galESvAge, dataset = "Gal"),
  transform(schESvAge, dataset = "Sch"),
  transform(keenESvAge, dataset = "Keen"),
  transform(melESvAge, dataset = "Mel")
)

y_min <- min(combinedES3$y, na.rm = TRUE)
y_max <- max(combinedES3$y, na.rm = TRUE)

# Separate plots with standardized y-axes
ggplot(combinedES3, aes(x = x, y = y, color = dataset)) +
  geom_line() +
  labs(title = "Effect Size vs Age",
       x = "Gestational Age",
       y = "Effect Size") +
  facet_wrap(~dataset, scales = "free_y") +
  ylim(y_min, y_max) +
  theme_minimal()
```
-- Weight effect sizes
```{r}
gal_pSDw <- sqrt((galefw_sdvalsm^2 + galefw_sdvalsf^2)/2)
sch_pSDw <- sqrt((schefw$F_SD..mm.^2 + schefw$M_SD..mm.^2)/2)
keen_pSDw <- sqrt((keen$weight_sd_boys_g^2 + keen$weight_sd_girls_g^2)/2)
```

```{r}
galESw <- galefw_diff/gal_pSDw
schESw <- schefw_diff/sch_pSDw
keenESw <- keenefw_diff/keen_pSDw
```

```{r}
galESwvAge <- data.frame(x = galefw$GA..Weeks..g., y = galESw)
schESwvAge <- data.frame(x = schefw$F_GA..Weeks., y = schESw)
keenESwvAge <- data.frame(x = keen$gestationweeks, y = keenESw)
```

```{r}
combinedW <- rbind(
  transform(galESwvAge, group = "gal_w"),
  transform(schESwvAge, group = "sch_w"),
  transform(keenESwvAge, group = "keen_w")
)

ggplot(combinedW, aes(x = x, y = y, color = group)) +
  geom_line() +
  labs(title = "Plot of Effect Size (Weight) vs Gestational Age",
       x = "Gestational Age",
       y = "Effect Size") +
  theme_minimal()
```
```{r}
y_min_w <- min(combinedW$y, na.rm = TRUE)
y_max_w <- max(combinedW$y, na.rm = TRUE)

#  Separate plots with standardized y-axes
ggplot(combined_dataw, aes(x = x, y = y, color = group)) +
  geom_line() +
  labs(title = "Plot of Effect Size (Weight) vs Gestational Age",
       x = "Gestational Age",
       y = "Effect Size_W") +
  facet_wrap(~group, scales = "free_y") +
  ylim(y_min_w, y_max_w) + 
  theme_minimal()
```
```{r}
ggplot(combined_dataw, aes(x = x, y = y, color = group)) +
  geom_line() +
  labs(title = "Plot of Effect Size (Weight) vs Gestational Age",
       x = "Gestational Age",
       y = "Effect Size_W") +
  facet_wrap(~group, scales = "free_y") +
    theme_minimal()
```
-- Length

```{r}
keenl_pSD <- sqrt((keen$weight_sd_boys_g^2 + keen$weight_sd_girls_g^2)/2)
keenlES <- keen_diffl/keenl_pSD
keenESvAge <- data.frame(x = keen$gestationweeks, y = keenlES) %>%
  na.omit()

ggplot(keenESvAge, aes(x = x, y = y)) +
  geom_line() +
  labs(title = "Plot of Effect Size (Length) vs Gestational Age",
       x = "Gestational Age",
       y = "Effect Size_L") +
  theme_minimal()
```
```{r}
length(keen$gestationweeks)
length(keenlES)
```

--- Adjusted Effect Sizes ---
```{r}
#Calculate Adjusted Effect Sizes
galESAdjW <- galES-galESw
schESAdjW <- schES-schESw
keenESAdjW <- keenES-keenESw
keenESAdjL <- keenES-keenlES

galESDiv <- galES/galESw
schESDiv <- schES/schESw
keenESDiv <- keenES/keenESw
keenESDivl <- keenES/keenlES

schESAdjAC <- schES-schacES
melESAdjAC <- melES-melESac

schESDivvAC <- schES/schacES
melESDivvAC <- melES/melESac

melESAdjFL <- melES-melESfl
melESDivvFL <- melES/melESfl

```

```{r}
#Data Frames for Adjusted Effect Sizes
galESAdjvAge <- data.frame(x = galefw$GA..Weeks..g., y = galESAdjW)
schESAdjvAge <- data.frame(x = schefw$F_GA..Weeks., y = schESAdjW)
keenESAdjvAge <- data.frame(x = keen$gestationweeks, y = keenESAdjW)
keenlESAdjvAge <- data.frame(x = keen$gestationweeks, y = keenESAdjL)

galESDivvAge <- data.frame(x = galefw$GA..Weeks..g., y = galESDiv)
schESADivvAge <- data.frame(x = schefw$F_GA..Weeks., y = schESDiv)
keenESDivvAge <- data.frame(x = keen$gestationweeks, y = keenESDiv)
keenlESDivvAge <- data.frame(x = keen$gestationweeks, y = keenESDivl)

schESAdjACvAge <- data.frame(x = schefw$F_GA..Weeks., y = schESAdjAC)
melESAdjACvAge <- data.frame(x = melESvAge$x, y = melESAdjAC)

schESDivvACvAge <- data.frame(x = schefw$F_GA..Weeks., y = schESDivvAC)
melESDivvACvAge <- data.frame(x = melESvAge$x, y = melESDivvAC)

melESAdjFLvAge <- data.frame(x = melESvAge$x, y = melESAdjFL)
melESDivvFLvAge <- data.frame(x = melESvAge$x, y = melESDivvFL)
```

```{r}
# Adjusted Effect Size (HC-W)
weightadj <- rbind(
  transform(galESAdjvAge, source = "Gal"),
  transform(schESAdjvAge, source = "Sch"),
  transform(keenESAdjvAge, source = "Keen")
)

adjw1 <- ggplot(weightadj, aes(x = x, y = y, color = source)) +
  geom_line() +
  labs(
    title = "Adjusted Effect Size (HC-W) vs Gestational Age",
    x = "Gestational Age",
    y = "Adjusted ES"
  ) +
  theme_minimal()
adjw1
```

```{r}
# Adjusted Effect Size (HC/W)
weightadj1 <- rbind(
  transform(galESDivvAge, source = "Gal"),
  transform(schESADivvAge, source = "Sch"),
  transform(keenESDivvAge, source = "Keen")
)

adjw2 <- ggplot(weightadj1, aes(x = x, y = y, color = source)) +
  geom_line() +
  labs(
    title = "Adjusted Effect Size (HC/W) vs Gestational Age",
    x = "Gestational Age",
    y = "Adjusted ES"
  ) +
  theme_minimal()
adjw2
```

```{r}
# Adjusted Effect Size (HC-L) and Adjusted Effect Size (HC/L)
ggplot(keenESAdjvAge, aes(x = x, y = y)) +
  geom_line() +
  labs(title = "Adjusted Effect Size (HC-L) vs Gestational Age",
       x = "Gestational Age",
       y = "Adjusted ES") +
  theme_minimal()

ggplot(keenESDivvAge, aes(x = x, y = y)) +
  geom_line() +
  labs(title = "Adjusted Effect Size (HC/L) vs Gestational Age",
       x = "Gestational Age",
       y = "Adjusted ES") +
  theme_minimal()
```

```{r}
# Adjusted Effect Sizes (HC-AC) and Adjusted Effect Sizes (HC/AC)
ggplot() +
  geom_line(data = schESAdjACvAge, aes(x = x, y = y), color = "red") +
  geom_line(data = melESAdjACvAge, aes(x = x, y = y), color = "blue") +
  labs(title = "Adjusted Effect Sizes (HC-AC) vs Gestational Age",
       x = "Gestational Age",
       y = "Adjusted ES") +
  theme_minimal()

ggplot() +
  geom_line(data = schESDivvACvAge, aes(x = x, y = y), color = "red") +
  geom_line(data = melESDivvACvAge, aes(x = x, y = y), color = "blue") +
  labs(title = "Adjusted Effect Sizes (HC/AC) vs Gestational Age",
       x = "Gestational Age",
       y = "Adjusted ES") +
  theme_minimal()
```
```{r}
# Adjusted Effect Size (HC/L) and Adjusted Effect Size (HC/L)
ggplot(melESAdjFLvAge, aes(x = x, y = y)) +
  geom_line() +
  labs(title = "Adjusted Effect Size (HC/L) vs Gestational Age",
       x = "Gestational Age",
       y = "Adjusted ES") +
  theme_minimal()

ggplot(melESDivvFLvAge, aes(x = x, y = y)) +
  geom_line() +
  labs(title = "Adjusted Effect Size (HC/L) vs Gestational Age",
       x = "Gestational Age",
       y = "Adjusted ES") +
  theme_minimal()
```


